// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJjJxpG4yC83f9gDYknrCNlhmy1190_AQ',
    appId: '1:642966539184:web:74f66ac061ce7fc7a6a475',
    messagingSenderId: '642966539184',
    projectId: 'shelflifechecker',
    authDomain: 'shelflifechecker.firebaseapp.com',
    storageBucket: 'shelflifechecker.firebasestorage.app',
    measurementId: 'G-BWDG7XG6TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5kGP-XXFjc-1oWqoIuS99Wu3BOu-apy4',
    appId: '1:642966539184:android:834a9548c4ee9feaa6a475',
    messagingSenderId: '642966539184',
    projectId: 'shelflifechecker',
    storageBucket: 'shelflifechecker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEdwqBOdf9Ge5EWoRCnifnxjnBngTZbVo',
    appId: '1:642966539184:ios:a5338481eb84a11ea6a475',
    messagingSenderId: '642966539184',
    projectId: 'shelflifechecker',
    storageBucket: 'shelflifechecker.firebasestorage.app',
    iosBundleId: 'com.example.shelfLifeChecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEdwqBOdf9Ge5EWoRCnifnxjnBngTZbVo',
    appId: '1:642966539184:ios:a5338481eb84a11ea6a475',
    messagingSenderId: '642966539184',
    projectId: 'shelflifechecker',
    storageBucket: 'shelflifechecker.firebasestorage.app',
    iosBundleId: 'com.example.shelfLifeChecker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJjJxpG4yC83f9gDYknrCNlhmy1190_AQ',
    appId: '1:642966539184:web:6d9a69a3fc92589ca6a475',
    messagingSenderId: '642966539184',
    projectId: 'shelflifechecker',
    authDomain: 'shelflifechecker.firebaseapp.com',
    storageBucket: 'shelflifechecker.firebasestorage.app',
    measurementId: 'G-ZLE7R82ZJ7',
  );
}
